def tipos_documentos():
    tipos_documentos = [
    "Externo",
    "Acompanhamento de Ações - ESCOLA DA HORA 1ºSEM",
    "Acórdão",
    "Acordo de Coop. SEM Compartilhamento de Rec Patrim",
    "Acordo de Nível de Serviço (ANS)",
    "Análise",
    "Anexo - Tesouro - Cota Extra (SEFAZ)",
    "Anexo A: Ficha de Inscrição - Ações Inovadoras",
    "Anexo B: Termo de Compromisso - Ações Inovadoras",
    "Anexo C: Termo de Concordância - Ações Inovadoras",
    "Anexo IV - Termo de Liberação do Servidor",
    "Anexo V - Termo de Compromisso do Servidor",
    "Anexo VI - Declaração Exec. Ativ. Servidor Público",
    "Ap. Contrato/Distrato - Op Logístico c/ Emp. Impor",
    "Ata Registro de Preço - Bens e Serviços COVID-19",
    "Ata Registro de Preço Serv Cont COM MDO Exclusiva",
    "Ata Registro de Preço Serv Cont SEM MDO Exclusiva",
    "Ata Registro de Preço Serviço Não Continuado",
    "Ata de Registro de Preços",
    "Ata de Reunião",
    "Ata",
    "Atestado",
    "Atesto de Bens/Serviços sem Contrato",
    "Atesto de Locação de Imóveis com Contrato Vigente",
    "Atesto de Locação de Imóveis sem Contrato Vigente",
    "Atesto de Materiais",
    "Atesto de Serviço Terceirizado",
    "Ato de Concessão",
    "Ato de Credenciamento",
    "Atualização de SERVIDOR no Portal AL Digital",
    "Avaliação de Curso de Capacitação - Instrutor EGAL",
    "Avaliação de Desempenho Anual - IN 05/22",
    "Avaliação de Desempenho Estágio Probatório IN06/22",
    "Avaliação de Desempenho",
    "Avaliação do Desempenho",
    "Aviso de Audiência Pública",
    "Aviso de Consolidação de Demandas",
    "Aviso de Contratação Direta",
    "Aviso de Cotação de Preço",
    "Aviso de Delegação de Competência",
    "Aviso de Licitação",
    "Aviso de Reabertura de Licitação",
    "Aviso de Revogação de Licitação",
    "Aviso de Solicitação de Demanda",
    "Aviso de Suspensão",
    "Cadastro Ordenador de Despesa SIAFE",
    "Cadastro de Credores/Fornecedores no SIAFE",
    "Cadastro de Gestores Financeiros no SIAFE",
    "Cadastro de Iniciativa",
    "Cadastro de Usuário no SIAFE",
    "Carta",
    "Certidão de Aposentadoria Voluntária",
    "Certidão",
    "Certificado",
    "CheckList - Liberação pelo CPOF",
    "CheckList - Processos Dispensa COVID19",
    "CheckList - Processos Indenizatório",
    "Checklist - Proc Adiant Numerário Enfrent a COVID",
    "Checklist - Processos Requisição Administrativa",
    "Checklist - Processos de Contratos e Convênios",
    "Checklist",
    "Comunicação de Incidente de Segurança",
    "Comunicação",
    "Contrato - Contratação Direta - Serviços com DEMO",
    "Contrato Dispensa ou Pregão Bens COVID-19",
    "Contrato Dispensa ou Pregão Serviços COVID-19",
    "Contrato Serviço Continuado SEM MDO Exclusiva",
    "Contrato",
    "Convênio",
    "Cotação de Fornecedor",
    "Decisão de Recurso Administrativo",
    "Decisão",
    "Declaração Permanecer Laborando Administrativo",
    "Declaração de Acumulação de Cargos Administrativo",
    "Declaração de Atendimento de Diligência",
    "Declaração de Atualização Cadastral",
    "Declaração de Permanência nas Funções",
    "Declaração de Pretensão ao Afastamento das Funções",
    "Declaração de Tempo de Contribuição ao RGPS - DTC",
    "Declaração de bens PF/PC",
    "Declaração do Ord. de Despesa Programa de Estágio",
    "Declaração",
    "Desligamento de Conveniado",
    "Despacho",
    "Despesas Covid",
    "Diagnóstico",
    "Diligência",
    "Documento de Formalização da Demanda (DFD)",
    "Documento de Formalização de Demanda - DFD",
    "Dotação Orçamentária",
    "E-mail",
    "Edital - Chamamento Público - Termo de Colaboração",
    "Edital - Chamamento Público - Termo de Fomento",
    "Edital - Concorrência",
    "Edital - Obras - Tomada de Preços",
    "Edital - Pregão - Serviços de Engenharia",
    "Edital - Pregão",
    "Edital - Serviço Continuado COM MDO Exclusiva",
    "Edital - Serviço Continuado SEM MDO Exclusiva",
    "Edital - Serviços Não Continuados",
    "Edital de Convocação",
    "Edital",
    "Ementa",
    "Encaminhamento de Conveniado",
    "Estudo Técnico Preliminar - ETP Compra",
    "Estudo Técnico Preliminar - ETP Serviço",
    "Estudo Técnico Preliminar",
    "Exposição de Motivos",
    "Exposição",
    "Extrato de Contrato",
    "Extrato",
    "Extratos de Ata de Registro de Preços",
    "Ficha Cadastro Responsáveis Contratos e Convênios",
    "Ficha de Inscrição Medalha do Mérito Silvio Vianna",
    "Formulário Acesso à Rede WIFI",
    "Formulário Contratação Direta",
    "Formulário Inscrição Dívida Ativa Não Tributária",
    "Formulário Padrão Convênios (SEFAZ)",
    "Formulário Recurso Chamada Pública Administrativo",
    "Formulário Solicitação Acesso Portal do Servidor",
    "Formulário Utilização da Ata de Registro de Preço",
    "Formulário de Aprovação (CPOF)",
    "Formulário de Cadastro de Veículo",
    "Formulário de Conformidade de Usuários (SEFAZ)",
    "Formulário de Licitação",
    "Formulário de Obras Públicas",
    "Formulário de Plano de Ação",
    "Formulário de Prestação de Contas do TED",
    "Formulário de Solicitação de Gravação de Áudio",
    "Formulário de Solicitação de Imagem",
    "Formulário para Interposição de Recurso",
    "Formulário para Solicitação de Curso Livre EAD",
    "GEAP - Capa do Processo",
    "GEAP - Primeiro Atendimento",
    "GEAP - Sumário Psicossocial",
    "Identificação do Contrato",
    "Informativo",
    "Instrução Normativa",
    "Integração de Sistemas com o SEI!",
    "Julgamento",
    "Justificativa de Crédito",
    "Laudo para Readaptação Funcional",
    "Laudo",
    "Listas de Verificação - Compras e Serviços",
    "Listas de Verificação - Contratação Direta",
    "Livro de Ocorrência das Equipes de Plantão",
    "Livro de Ocorrência do Plantão",
    "Mapa Comparativo de Preço - Fornecedor",
    "Mapa Comparativo de Preço",
    "Mapa de Análise de Riscos da Contratação",
    "Memorando",
    "Memorial",
    "Minuta de Decreto",
    "Minuta de Instrução Normativa",
    "Minuta de Lei",
    "Minuta de Portaria Regulamentar",
    "Minuta",
    "Notificação / Citação / Intimação",
    "Notificação",
    "Ofício Circular",
    "Ofício",
    "Ordem de Fornecimento",
    "Ordem",
    "Parcerias - Termo de Colaboração/Termo de Fomento",
    "Parecer Técnico - Selo da Diversidade",
    "Parecer Técnico",
    "Parecer",
    "Passagens para Terceiros",
    "Perfil Profissiográfico Previdenciário - PPP",
    "Planilha de Custo - Pesquisa com Fornecedor",
    "Planilha de Custo - Portal Compras Governamentais",
    "Planilha de Justificativa de Ponto",
    "Plano Orçamentário - Cadastramento",
    "Plano de Aula",
    "Plano de Suprimentos",
    "Plano de Trabalho - ANEXO II",
    "Plano",
    "Portaria Conjunta",
    "Portaria de Nomeação de Núcleo SEI",
    "Portaria",
    "Posição de Liberação de Recursos do FECOEP",
    "Prestação de Contas da Passagem (ANEXO V)",
    "Prestação de Contas de Adiantamento (ANEXO II)",
    "Prestação de Contas de Diárias (ANEXO III)",
    "Projeto de Lei",
    "Projeto",
    "Proposta de Curso",
    "Questionário",
    "RH: Concessão do Benefício Especial",
    "Recibo",
    "Registro Plantão Social",
    "Registro de Reunião",
    "Regulamento de Edital",
    "Relatório Síntese do Curso",
    "Relatório de Atividades - ANEXO III",
    "Relatório de Auditoria",
    "Relatório de Contribuições",
    "Relatório de Desempenho do Projeto",
    "Relatório de Evidências - Selo da Diversidade",
    "Relatório de Impacto à Proteção de Dados Pessoais",
    "Relatório de Levantamento de Vagas de Estágio",
    "Relatório",
    "Req. Contestação de Cálculos do IPM Prefeitura",
    "Req. de Sol. de DAC, Doc, Arq Fiscais ou Info IPM",
    "Requerimento Afastamento Estudo/Missão no Exterior",
    "Requerimento Afastamento Exercício Mandato Eletivo",
    "Requerimento Análise Projeto Reanálise (CASAL)",
    "Requerimento Análise Projeto Revisão (CASAL)",
    "Requerimento Aposentadoria Especial Ativ. à Saúde",
    "Requerimento Aposentadoria Especial Deficiência",
    "Requerimento Aposentadoria Especial de Policial",
    "Requerimento Aposentadoria Especial de Professor",
    "Requerimento Aposentadoria Incapacidade Permanente",
    "Requerimento Aposentadoria T. Contribuição e Idade",
    "Requerimento Averbação L. Premio T. Contribuição",
    "Requerimento Averbação Licença Premio não Gozada",
    "Requerimento Averbação Tempo Serviço/Contribuição",
    "Requerimento Cancel Insc Plano Benfefíc ALPREVCOMP",
    "Requerimento Chamada Pública Administrativo",
    "Requerimento Declaração de Tempo de Contribuição",
    "Requerimento Desaverbação Licença Prêmio Especial",
    "Requerimento Desaverbação T. Serviço/Contribuição",
    "Requerimento Geral (UNCISAL)",
    "Requerimento Licença Desempenho Mandato Classista",
    "Requerimento Licença Trato Interesses Particulares",
    "Requerimento de Abono Permanência",
    "Requerimento de Acesso Sistemas da Solução Digital",
    "Requerimento de Adicional Noturno",
    "Requerimento de Adicional Serviço Extraordinário",
    "Requerimento de Adicional por Tempo Serviço",
    "Requerimento de Alteração Demonstrativo Pagamento",
    "Requerimento de Aposentadoria Compulsória",
    "Requerimento de Aposentadoria Voluntária",
    "Requerimento de Aposentadoria por Invalidez",
    "Requerimento de Averbação de Licença Prêmio",
    "Requerimento de Candidatura",
    "Requerimento de Certidão de Tempo de Serviço",
    "Requerimento de Certidão do Ato Nomeação e Outros",
    "Requerimento de Concessão da Aposentadoria",
    "Requerimento de Concessão de Licença Prêmio",
    "Requerimento de Concessão do Benefício Especial",
    "Requerimento de Cumprimento de Ordem Judicial IPM",
    "Requerimento de Desaverbação de Tempo Excedente",
    "Requerimento de Desistência de Pedido",
    "Requerimento de Exoneração",
    "Requerimento de Gozo de Férias",
    "Requerimento de Gratificação Natalina",
    "Requerimento de Inscrição - Selo da Diversidade",
    "Requerimento de Licença para Acompanhar Cônjuge",
    "Requerimento de Licença para Atividade Política",
    "Requerimento de Licença para Capacitação",
    "Requerimento de Licença",
    "Requerimento de Mudança de Classe Administrativo",
    "Requerimento de Pagamento Verbas Rescisórias",
    "Requerimento de Progressão Horizontal",
    "Requerimento de Progressão Vertical",
    "Requerimento de Vacância",
    "Requerimento",
    "Resolução",
    "Resultado de Licitação",
    "Sol. Aquisição Bens/Prestação Serviços (ANEXO I)",
    "Solicitação de Acesso via VPN (ITEC)",
    "Solicitação de Adiantamento (ANEXO I)",
    "Solicitação de Adiantamento (FDRH)",
    "Solicitação de Colaborador",
    "Solicitação de Copos de Água (CASAL)",
    "Solicitação de Cota Extra de Combustível",
    "Solicitação de Diárias para Viagem (ANEXO II)",
    "Solicitação de Jeton",
    "Solicitação de Passagem (ANEXO II)",
    "Solicitação de Reavaliação (UNCISAL)",
    "Solicitação de Repactuação Iniciativas e Projetos",
    "Solicitação de Utilização de Espaço (UNCISAL)",
    "TR - Compras",
    "TR - Contratação Direta - Compras",
    "TR - Contratação Direta - Engenharia",
    "TR - Contratação Direta - Serviços com DEMO",
    "TR - Contratação Direta - Serviços",
    "TR - Obras e Serviços de Engenharia",
    "TR - Serviços com DEMO",
    "TR - Serviços",
    "Termo Aditivo - Bens - Prazo e Objeto",
    "Termo Aditivo - Serv. Cont. com MDO - Prazo/Objeto",
    "Termo Aditivo - Serv. Cont. com MDO - Prazo",
    "Termo Aditivo - Serv. Cont. sem MDO - Objeto",
    "Termo Aditivo - Serv. Cont. sem MDO - Prazo/Objeto",
    "Termo Aditivo - Serv. Cont. sem MDO - Prazo",
    "Termo Aditivo - Serviços não Cont - Prazo e Objeto",
    "Termo Aditivo - Serviços não Continuados - Objeto",
    "Termo Aditivo - Serviços não Continuados - Prazo",
    "Termo Aditivo de Proteção de Dados Pessoais",
    "Termo Aditivo do Termo de Execução Descentralizada",
    "Termo Aditivo",
    "Termo de Abertura de Projeto (TAP)",
    "Termo de Abertura do Projeto",
    "Termo de Aceite Parcial do Projeto",
    "Termo de Aceite e Encerramento do Projeto",
    "Termo de Adesão ao Trabalho Remoto (ANEXO I)",
    "Termo de Adjudicação",
    "Termo de Apostilamento para Aposentadoria",
    "Termo de Apostilamento",
    "Termo de Autorização e Respon. de aparelho Móvel",
    "Termo de Colaboração",
    "Termo de Compromisso Proteção de Dados Pessoais",
    "Termo de Compromisso e Manutenção de Sigilo",
    "Termo de Compromisso",
    "Termo de Confidencialidade - Geral",
    "Termo de Contrato - Compras",
    "Termo de Contrato - Contratação Direta - Compras",
    "Termo de Contrato - Contratação Direta - Serviços",
    "Termo de Contrato - Contratação Direta/Engenharia",
    "Termo de Contrato - Obras e Serviços de Engenharia",
    "Termo de Contrato - Serviços com DEMO",
    "Termo de Contrato - Serviços",
    "Termo de Cooperação",
    "Termo de Encerramento de Trâmite Físico",
    "Termo de Encerramento do Processo",
    "Termo de Encerramento do Projeto",
    "Termo de Execução Descentralizada",
    "Termo de Fomento",
    "Termo de Guarda de Mídia",
    "Termo de Homologação",
    "Termo de Posse",
    "Termo de Ratificação de Dispensa",
    "Termo de Referência - Ser Cont SEM Mao Obra Exclus",
    "Termo de Responsabilidade - Programa de Estágio",
    "Termo de Responsabilidade da Folha",
    "Termo de Responsabilidade para Cadastro",
    "Termo de Responsabilidade para Gestores e Fiscais",
    "Termo de Responsabilidade para uso dos Sistemas",
    "Termo",
    "Vistas",
    "Voto"
]
    return tipos_documentos
